services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  sleek-airflow:
    image: sleek-airflow:latest
    volumes:
      - ./tmp:/tmp
      - ./dags:/opt/airflow/dags
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=10
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    command: airflow standalone

volumes:
  postgres-db-volume: